version: '3.8'

services:
  postgres:
    image: "postgres"
    container_name: "postgres-spring-cloud-openfeign-sample"
    hostname: "postgres-001"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: "/data/postgres"
    ports:
      - "15432:5432"
    volumes:
      - type: volume
        source: "postgres-001"
        target: "/data/postgres"
    networks:
      - "network-spring-cloud-openfeign-sample.local"
    restart: unless-stopped
#---------------------------------------------------------------------------------------------------------------------
networks:
  network-spring-cloud-openfeign-sample.local:
    name: "network-spring-cloud-openfeign-sample.local"
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
#---------------------------------------------------------------------------------------------------------------------
volumes:
  postgres-001:
    name: "postgres-001"
