CREATE TABLE T_ORDER (
  ID BIGSERIAL PRIMARY KEY,
  ACCOUNT_ID  UUID NOT NULL,
  STATUS VARCHAR NOT NULL,
  TOTAL DECIMAL NOT NULL,
  CREATION_DATE TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  VERSION BIGINT
);
