spring.config.activate.on-profile: default
server.servlet.context-path: / # Context path of the application.
server.port: 9080 # Server HTTP port.
spring.main.allow-bean-definition-overriding: true # Enable bean override

# Postgres
spring.datasource.postgres.type: com.zaxxer.hikari.HikariDataSource
spring.datasource.postgres.jdbcUrl: jdbc:postgresql://${POSTGRES_HOST:localhost}:15432/postgres
spring.datasource.postgres.driver-class-name: org.postgresql.Driver
spring.datasource.postgres.username: postgres
spring.datasource.postgres.password: postgres

# https://github.com/brettwooldridge/HikariCP#configuration-knobs-baby
spring.datasource.postgres.pool-name: HikariPool
spring.datasource.postgres.connection-timeout: 20000
spring.datasource.postgres.minimum-idle: 5
spring.datasource.postgres.maximum-pool-size: 12
spring.datasource.postgres.idle-timeout: 300000
spring.datasource.postgres.max-lifetime: 1200000
spring.datasource.postgres.auto-commit: false

# JPA specific configs
spring.jpa.open-in-view: false
#spring.jpa.properties.hibernate.connection.provider_class: org.hibernate.hikaricp.internal.HikariCPConnectionProvider
spring.jpa.database-platform: org.hibernate.dialect.PostgreSQL95Dialect
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQL95Dialect
spring.jpa.properties.hibernate.show_sql: false
spring.jpa.properties.hibernate.format_sql: true
spring.jpa.properties.hibernate.use_sql: true
spring.jpa.properties.hibernate.hibernate.dialect: true
spring.jpa.properties.hibernate.id.new_generator_mappings: false
spring.jpa.properties.hibernate.search.autoregister_listeners: false
spring.jpa.properties.hibernate.bytecode.use_reflection_optimizer: false

# Flyway
spring.flyway.enabled: false
spring.flyway.locations: classpath:/db/migration

# Feign -- https://docs.spring.io/spring-cloud-openfeign/docs/current/reference/html/appendix.html
feign.client.config.default:
  connectTimeout: 5000
  readTimeout: 5000
feign.compression.request.enabled: false
feign.compression.response.enabled: false
feign.okhttp.enabled: true

# https://resilience4j.readme.io/docs/circuitbreaker
resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      failureRateThreshold: 50
      slowCallRateThreshold: 100
      slowCallDurationThreshold: 60000ms
      permittedNumberOfCallsInHalfOpenState: 10
      maxWaitDurationInHalfOpenState: 0
      slidingWindowType: "COUNT_BASED"
      slidingWindowSize: 100
      minimumNumberOfCalls: 100
      waitDurationInOpenState: 6000ms
      automaticTransitionFromOpenToHalfOpenEnabled: false
      max-wait-duration-in-half-open-state: 1ms
      recordExceptions:
      ignoreExceptions:
  instances:
    account-service:
      baseConfig: default
# https://resilience4j.readme.io/docs/retry
resilience4j.retry:
  configs:
    default:
      maxRetryAttempts: 3
      waitDuration: 100
      retryExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.util.concurrent.TimeoutException
        - java.io.IOException
  instances:
    account-service:
      baseConfig: default
# https://resilience4j.readme.io/docs/bulkhead
resilience4j.bulkhead:
  configs:
    default:
      maxWaitDuration: 10ms
      maxConcurrentCalls: 10
  instances:
    account-service:
      baseConfig: default

account-service.url: localhost:8080
